/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.trade.client.jersey.api;

import io.swagger.trade.client.jersey.ApiException;
import io.swagger.trade.client.jersey.model.Error;
import io.swagger.trade.client.jersey.model.NotFound;
import io.swagger.trade.client.jersey.model.ResourceEventFilterDescriptionArray;
import io.swagger.trade.client.jersey.model.ResourceEventFilterDescriptionArrayWithLinks;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourceEventFilterApi
 */
@Ignore
public class ResourceEventFilterApiTest {

    private final ResourceEventFilterApi api = new ResourceEventFilterApi();

    
    /**
     * Find a resource event filter description by Id
     *
     * Provides one or more available &#x60;resourceEventFilter&#x60; descriptions based on the provided parameters. Optional query parameter of **eventType** filters result list by the event types of even filter descriptions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResourceEventFilterDirectlyTest() throws ApiException {
        String resourceEventFilterId = null;
        String eventType = null;
        ResourceEventFilterDescriptionArray response = api.getResourceEventFilterDirectly(resourceEventFilterId, eventType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets all available &#x60;resourceEventFilter&#x60; resources. Optional query parameter of **start** and **size** enable pagination of the collection of resource event filter resources, param **eventType** filters result list by the event types of even filter descriptions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getResourceEventFiltersTest() throws ApiException {
        Integer start = null;
        Integer size = null;
        String eventType = null;
        ResourceEventFilterDescriptionArrayWithLinks response = api.getResourceEventFilters(start, size, eventType);

        // TODO: test validations
    }
    
}
