/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.swagger.trade.client.jersey.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;
/**
 * DataObjectInstance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-05T17:17:13.418+02:00")
public class DataObjectInstance implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("dataObjectName")
  private String dataObjectName = null;

  @JsonProperty("correlationProperties")
  private CorrelationPropertyArray correlationProperties = null;

  @JsonProperty("status")
  private InstanceStatusEnum status = null;

  public DataObjectInstance id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DataObjectInstance href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public DataObjectInstance createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public DataObjectInstance dataObjectName(String dataObjectName) {
    this.dataObjectName = dataObjectName;
    return this;
  }

   /**
   * Get dataObjectName
   * @return dataObjectName
  **/
  public String getDataObjectName() {
    return dataObjectName;
  }

  public void setDataObjectName(String dataObjectName) {
    this.dataObjectName = dataObjectName;
  }

  public DataObjectInstance correlationProperties(CorrelationPropertyArray correlationProperties) {
    this.correlationProperties = correlationProperties;
    return this;
  }

   /**
   * Get correlationProperties
   * @return correlationProperties
  **/
  public CorrelationPropertyArray getCorrelationProperties() {
    return correlationProperties;
  }

  public void setCorrelationProperties(CorrelationPropertyArray correlationProperties) {
    this.correlationProperties = correlationProperties;
  }

  public DataObjectInstance status(InstanceStatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public InstanceStatusEnum getStatus() {
    return status;
  }

  public void setStatus(InstanceStatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataObjectInstance dataObjectInstance = (DataObjectInstance) o;
    return Objects.equal(this.id, dataObjectInstance.id) &&
        Objects.equal(this.href, dataObjectInstance.href) &&
        Objects.equal(this.createdBy, dataObjectInstance.createdBy) &&
        Objects.equal(this.dataObjectName, dataObjectInstance.dataObjectName) &&
        Objects.equal(this.correlationProperties, dataObjectInstance.correlationProperties) &&
        Objects.equal(this.status, dataObjectInstance.status);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(id, href, createdBy, dataObjectName, correlationProperties, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataObjectInstance {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    dataObjectName: ").append(toIndentedString(dataObjectName)).append("\n");
    sb.append("    correlationProperties: ").append(toIndentedString(correlationProperties)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

