/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.swagger.trade.client.jersey.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets InstanceStatusEnum
 */
public enum InstanceStatusEnum {
  
  CREATED("created"),
  
  INITIALIZED("initialized"),
  
  ARCHIVED("archived");

  private String value;

  InstanceStatusEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static InstanceStatusEnum fromValue(String text) {
    for (InstanceStatusEnum b : InstanceStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
            return b;
        }
    }
    return null;
  }
}

