/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.swagger.trade.client.jersey.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;
/**
 * InvalidInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-05T17:17:13.418+02:00")
public class InvalidInput implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("property")
  private String property = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("example")
  private String example = null;

  @JsonProperty("moreInfo")
  private String moreInfo = null;

  public InvalidInput property(String property) {
    this.property = property;
    return this;
  }

   /**
   * Get property
   * @return property
  **/
  public String getProperty() {
    return property;
  }

  public void setProperty(String property) {
    this.property = property;
  }

  public InvalidInput message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public InvalidInput example(String example) {
    this.example = example;
    return this;
  }

   /**
   * Get example
   * @return example
  **/
  public String getExample() {
    return example;
  }

  public void setExample(String example) {
    this.example = example;
  }

  public InvalidInput moreInfo(String moreInfo) {
    this.moreInfo = moreInfo;
    return this;
  }

   /**
   * Get moreInfo
   * @return moreInfo
  **/
  public String getMoreInfo() {
    return moreInfo;
  }

  public void setMoreInfo(String moreInfo) {
    this.moreInfo = moreInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvalidInput invalidInput = (InvalidInput) o;
    return Objects.equal(this.property, invalidInput.property) &&
        Objects.equal(this.message, invalidInput.message) &&
        Objects.equal(this.example, invalidInput.example) &&
        Objects.equal(this.moreInfo, invalidInput.moreInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(property, message, example, moreInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvalidInput {\n");
    
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("    moreInfo: ").append(toIndentedString(moreInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

