/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.trade.client.jersey.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;

/**
 * NotificationArrayWithLinks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T14:24:08.511+02:00")
public class NotificationArrayWithLinks implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("notifications")
  private NotificationArray notifications = null;

  @JsonProperty("links")
  private LinkArray links = null;

  public NotificationArrayWithLinks notifications(NotificationArray notifications) {
    this.notifications = notifications;
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  public NotificationArray getNotifications() {
    return notifications;
  }

  public void setNotifications(NotificationArray notifications) {
    this.notifications = notifications;
  }

  public NotificationArrayWithLinks links(LinkArray links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  public LinkArray getLinks() {
    return links;
  }

  public void setLinks(LinkArray links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationArrayWithLinks notificationArrayWithLinks = (NotificationArrayWithLinks) o;
    return Objects.equal(this.notifications, notificationArrayWithLinks.notifications) &&
        Objects.equal(this.links, notificationArrayWithLinks.links);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(notifications, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationArrayWithLinks {\n");
    
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

