/*
 * TraDE Middleware API
 * This is the API of the TraDE middleware.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: trade4chor@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.trade.client.jersey.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;

/**
 * NotificationWithLinks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-21T14:24:08.511+02:00")
public class NotificationWithLinks implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("notification")
  private Notification notification = null;

  @JsonProperty("links")
  private LinkArray links = null;

  public NotificationWithLinks notification(Notification notification) {
    this.notification = notification;
    return this;
  }

   /**
   * Get notification
   * @return notification
  **/
  public Notification getNotification() {
    return notification;
  }

  public void setNotification(Notification notification) {
    this.notification = notification;
  }

  public NotificationWithLinks links(LinkArray links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  public LinkArray getLinks() {
    return links;
  }

  public void setLinks(LinkArray links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationWithLinks notificationWithLinks = (NotificationWithLinks) o;
    return Objects.equal(this.notification, notificationWithLinks.notification) &&
        Objects.equal(this.links, notificationWithLinks.links);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(notification, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationWithLinks {\n");
    
    sb.append("    notification: ").append(toIndentedString(notification)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

